name: Aggiorna Mappa Allerta
on:
  push:
    paths:
      - 'dati_bollettino.json'
  workflow_dispatch: # <--- Questa riga permette l'avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Esegui Script
        run: python merge_script.py

      - name: Commit e Push
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add bollettino_comunale_live.geojson
          # Il comando seguente evita errori se non ci sono cambiamenti
          git commit -m "Forza aggiornamento bollettino" || exit 0
          git push
